apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: {{ .Values.container.port }}
  selector:
    app: {{ .Chart.Name }}
  type: {{ .Values.service.type }}

{{/*helm upgrade --install release-name --namespace default --values ./production.yml*/}}
