{{/*apiVersion: v1*/}}
{{/*kind: Service*/}}
{{/*metadata:*/}}
{{/*  name: {{ include "buildachart.fullname" . }}*/}}
{{/*  labels:*/}}
{{/*    {{- include "buildachart.labels" . | nindent 4 }}*/}}
{{/*spec:*/}}
{{/*  type: {{ .Values.service.type }}*/}}
{{/*  ports:*/}}
{{/*    - port: {{ .Values.service.port }}*/}}
{{/*      targetPort: http*/}}
{{/*      protocol: TCP*/}}
{{/*      name: http*/}}
{{/*  selector:*/}}
{{/*    {{- include "buildachart.selectorLabels" . | nindent 4 }}*/}}

{{/*---*/}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: {{ .Values.container.port }}
  selector:
    app: {{ .Chart.Name }}
  type: {{ .Values.service.type }}

{{/*helm upgrade --install release-name --namespace default --values ./production.yml*/}}
